name: Create new repo
on:
    workflow_dispatch:
        inputs:
            repository_name:
                description: 'Nombre del repositorio a procesar'
                required: true
                type: string
            port_run_id:
                description: 'ID de la ejecucion en Port'
                required: false
                type: string
            port_context:
                description: 'Contexto proporcionado por Port'
                required: false
                type: string
            blueprint_id:
                description: 'Nombre del blueprint'
                required: false
                type: string
jobs:
    generate-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            actions: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2
            - name: Crear nuevo
              env:
                GH_TOKEN: ${{ secrets.ORG_REPO_ACCESS }}
              run: |            
                ORG="nttdata-jr"
                REPO_NAME="nuevo-repo-$RANDOM"
                RESPONSE=$(curl -s -X POST https://api.github.com/orgs/$ORG/repos \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                -d "{\"name\":\"$REPO_NAME\", \"private\":true}")
                URL=$(echo "$RESPONSE" | jq -r '.html_url')
                echo "REPO_URL=$URL" >> $GITHUB_OUTPUT